### ISSUE TITLE
Cannot run / install specific versions of setup-envtest due to missing submodule tag

### ISSUE THREAD

**Issue by nathanperkins** [kubernetes-sigs/controller-runtime#2759] opened 2024-04-05 01:09 UTC
I'm getting a failure when trying to run a specific version of setup-envtest. We need to run an old version in our CI because the new version uses a go.mod with version `1.22.0` which isn't compatible with our CI's go toolchain.

```
go: sigs.k8s.io/controller-runtime/tools/setup-envtest@v0.17.2: module sigs.k8s.io/controller-runtime@v0.17.2 found, but does not contain package sigs.k8s.io/controller-runtime/tools/setup-envtest
```

My understanding is that this failure is because setup-envtest is a submodule in controller-runtime and needs it's own tag, like `tools/setup-envtest/v0.17.2`.

I'm having trouble finding the golang documentation which explains how submodules need their own tag to work properly :(

**Comment by pmalek** [comment] 2024-04-05 13:08
This is most likely a duplicate of #2744 and related to #2646

**Comment by nathanperkins** [comment] 2024-04-05 16:58
> This is most likely a duplicate of #2744 and related to #2646

You're right, thank you! I see there is a workaround if you install with `@branch`.

**Closed** 2024-04-05 17:04 UTC
