### ISSUE TITLE
Race condition in source.Channel loses events

### ISSUE THREAD

**Issue by shomron** [kubernetes-sigs/controller-runtime#961] opened 2020-05-22 22:32 UTC
There is race condition in `source.Channel` between `syncLoop()` (which drains the incoming `Source` events) and adding new destination channels for distribution:

```
cs.dest = append(cs.dest, dst)
```

The two are not synchronized and it is possible for the source channel to be drained from existing events before the destination channel is established. This will cause these events to be lost.

**Comment by alvaroaleman** [comment] 2020-05-23 01:47
I think this issue is a duplicate of #942

**Comment by shomron** [comment] 2020-05-23 02:08
Yes, this looks like the same issue 👍

**Closed** 2020-06-09 20:20 UTC
