### ISSUE TITLE
Support partial metadata informers / watches

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/controller-runtime#1086] opened 2020-07-29 21:20 UTC
Client-go has support for a metadata-only client and informer which can be found https://github.com/kubernetes/client-go/tree/36233866f1c7c0ad3bdac1fc466cb5de3746cfa2/metadata. This can be useful when users don't want to cache particular objects, but metadata is usually enough to receive notifications.

/milestone Next
/kind design
/cc @ncdc

**Comment by alvaroaleman** [comment] 2020-09-15 21:53
Closing as duplicate of https://github.com/kubernetes-sigs/controller-runtime/issues/1159 (Because I find the title of the latter more clear :) )
/close

**Closed** 2020-09-15 21:53 UTC
Labels: kind/design
