### ISSUE TITLE
Go Modules: Downstream project is breaking due to move of github.com/appscode/jsonpatch

### ISSUE THREAD

**Issue by connor1989** [kubernetes-sigs/controller-runtime#500] opened 2019-06-25 19:02 UTC
Downstream projects using go modules are running into issues since  `com/appscode/jsonpatch` has moved to `github.com/gomodules/jsonpatch`. Not sure if this is user error with go mod's. It's also worth mentioning the update occurred today.

Ex output:

```
go: finding github.com/appscode/jsonpatch latest
go: downloading github.com/appscode/jsonpatch v0.0.0-20190625112030-8287e15e901f
build command-line-arguments: cannot load github.com/appscode/jsonpatch: cannot find module providing package github.com/appscode/jsonpatch
```

Env:
`go version go1.12.5 darwin/amd64`

**Comment by lli-hiya** [comment] 2019-06-28 06:43
I am seeing exactly the same issue. Any workaround?

**Comment by Jingru** [comment] 2019-06-28 08:49
Same issue here.

**Comment by DirectXMan12** [comment] 2019-06-28 18:07
should've just been fixed by #499

**Closed** 2019-06-28 18:07 UTC
Labels: kind/bug, priority/important-longterm

**Comment by ghostsquad** [comment] 2019-07-17 01:45
I'm still having this problem.

```
go: finding sigs.k8s.io/controller-runtime/pkg/log/zap latest
go: finding sigs.k8s.io/controller-runtime/pkg/log latest
go: finding sigs.k8s.io/controller-runtime/pkg latest
build myproject: cannot load github.com/appscode/jsonpatch: cannot find module providing package github.com/appscode/jsonpatch
```

what am I doing wrong?

**Comment by alastor-erinyes** [comment] 2019-07-22 07:31
I hit this same issue as well.

```
go: extracting github.com/gomodules/jsonpatch v2.0.0+incompatible
go: finding github.com/appscode/jsonpatch v2.0.0+incompatible
go: finding sigs.k8s.io/controller-runtime/pkg/log latest
go: finding sigs.k8s.io/controller-runtime/pkg latest
build github.com/datarobot/DataRobot/execute/golang/testbin: cannot load github.com/appscode/jsonpatch: cannot find module providing package github.com/appscode/jsonpatch
```
I've tried a few `replace` directives in go.mod, but nothing is working so far.

**Comment by fspaniol** [comment] 2019-08-01 13:25
Was trying to follow this: https://book.kubebuilder.io/quick-start.html#create-a-project and faced the same issue:

```
kubebuilder init --domain fernando
go mod tidy
go: finding sigs.k8s.io/controller-runtime v0.2.0-beta.4
go: finding github.com/evanphx/json-patch v4.5.0+incompatible
go: gomodules.xyz/jsonpatch/v2@v2.0.0: unrecognized import path "gomodules.xyz/jsonpatch/v2" (https fetch: Get https://gomodules.xyz/jsonpatch/v2?go-get=1: net/http: TLS handshake timeout)
go: error loading module requirements
2019/08/01 15:07:19 exit status 1
```

Manually changing to `beta.2` in `go.mod` did the trick.

**Comment by seh** [comment] 2019-08-01 20:03
_(Cross posting:)_
If I try to fix this problem with _controller-runtime_, I run into kubernetes/client-go#584. If I try to fix that problem, I run into this problem.

It's not clear yet how to get both of them to work at the same time.

**Comment by DirectXMan12** [comment] 2019-08-06 00:51
@fspaniol probably a blip in that module's hosting.  Cannot reproduce now.

**Comment by saravanakumar-periyasamy** [comment] 2019-10-23 15:09
I still seeing the same error.

```
build command-line-arguments: cannot load github.com/appscode/jsonpatch: module github.com/appscode/jsonpatch@latest found (v2.0.1+incompatible), but does not contain package github.com/appscode/jsonpatch
```

**Comment by DirectXMan12** [comment] 2019-11-05 23:19
make sure you don't have the old version in your go.mod
