### ISSUE TITLE
non-namespaced objects namespace gets dropped

### ISSUE THREAD

**Issue by mjudeikis** [kubernetes-sigs/controller-runtime#543] opened 2019-07-27 16:46 UTC
I have namespaced objects creating non-namespaced objects and watch loop:

```
err = c.Watch(&source.Kind{Type: &apiextensionsapi.CustomResourceDefinition{}}, &handler.EnqueueRequestForOwner{
		IsController: true,
		OwnerType:    &apiv1alpha1.Request{},
})
if err != nil {
	return err
}

	// Watch for changes to primary resource crdrequest and requeue the owner Namespace
	return c.Watch(&source.Kind{Type: &apiv1alpha1.Request{}}, &handler.EnqueueRequestForObject{})
```

If `apiv1alpha1.Request` object gets created natively - watcher send me a request:
```
Request.Name=example-request Request.Namespace=test
```

But if Non-namespaced objects gets modified (which is owned by namespaced one) I get request:
```
Request.Name=example-request Request.Namespace=
```

Looks like during the lookup of owner object and resolution to the owner object itself namespace gets dropped somehow from the `request reconcile.Request` object 

:man_shrugging:

**Comment by mjudeikis** [comment] 2019-07-27 17:24
Basically workaround it with hack:
```
// HACK: Because we manage non-namespaced objects with namespaced objects
// sometimes we don't get namespace in the reconcile.Request. This is due to fact
// that owner field does not contain namespace of the owning object.
// Because of this we will get all namespaces of all potentially duplicate
// objects and just reconcile them all.
reconcileList := []reconcile.Request{}
if len(request.Namespace) == 0 {
objects, err := r.client.Requests(metav1.NamespaceAll).List(metav1.ListOptions{})
	if err != nil {
		return reconcile.Result{Requeue: true}, err
        }
	for _, req := range objects.Items {
		reconcileList = append(reconcileList, reconcile.Request{
			NamespacedName: types.NamespacedName{
				Name:      req.Name,
				Namespace: req.Namespace,
			},
		})
	}
	for _, req := range reconcileList {
		return r.Reconcile(req)
	}
} else {
	r.log = r.log.WithField("Request.Namespace", request.Namespace).WithField("Request.Name", request.Name)
	r.log.Info("Reconciling")
        return r.reconcoleRequest(request)
}
return reconcile.Result{Requeue: false}, nil
```

**Comment by DirectXMan12** [comment] 2019-08-06 00:58
owner references from namespaced objects to non-namespaced objects won't work, as you found out.  You'll need to keep track of them using a different mechanism.

**Comment by DirectXMan12** [comment] 2019-08-06 00:58
(perhaps an annotation, or similar)

**Comment by DirectXMan12** [comment] 2019-08-06 00:58
(closing for now since this is kind-of working as intended, in that upstream Kubernetes intended this and there's not much we can do about it)

**Closed by DirectXMan12** 2019-08-06 00:58 UTC
