### ISSUE TITLE
Update cache to implement client.Writer and update cache with updated objects returned from API server writes

### ISSUE THREAD

**Issue by robbie-demuth** [kubernetes-sigs/controller-runtime#2209] opened 2023-02-23 20:54 UTC
Context: https://kubernetes.slack.com/archives/CAR30FCJZ/p1677164004551529

When clients write objects with outdated resource versions, the API server returns HTTP 409 Conflict errors like the following:

```
Operation cannot be fulfilled on <KIND>.<GROUP> "<NAME>": the object has been modified; please apply your changes to the latest version and try again
```

When a write succeeds, the updated object, with updated resource version, is returned. Subsequent writes within the same reconcile loop can use the updated object to avoid the aforementioned errors. Subsequent writes from different reconcile loops, which first re-read the object from the cache, however, may fail depending on whether or not the underlying informer has received the update and updated the cache

Without explicit handling of HTTP 409 Conflict errors, operator owners may be mislead into thinking their operator is experiencing issues due to increments in `controller_runtime_reconcile_errors_total` when in fact it is behaving normally

I've opened this issue to discuss the idea of updating the cache to implement client.Writer in addition to client.Reader - with the client.Writer implementation updating the cache with the updated objects returned by the API server on writes

**Comment by FillZpp** [comment] 2023-02-24 03:43
> I've opened this issue to discuss the idea of updating the cache to implement client.Writer in addition to client.Reader - with the client.Writer implementation updating the cache with the updated objects returned by the API server on writes

I think it's a bad idea. The cache will be in a mess if there are input objects from both apiserver watch and user insert manually.

For example, an object was once in a version `v1`. Then you update the object twice, which makes the object changed to `v2` and `v3` in apiserver/etcd. If you directly put the `v3` object into cache, and then it gets an update event from apiserver to change it to `v2` (`v3` event has not been sent yet). Those event handlers will get wrong events:
- `v1` to `v3`
- `v3` to `v2`
- `v2` to `v3` finally

(We can't assume that the `resourceVersion` always be a string of increasing integer and use it to compare which one is newer)

To solve your problem, you could use `retry.RetryOnConflict` to do a quick retry. And if it still fails, which may be caused by slow network transmission or apiserver suffering pressure, you have to return an error in reconcile and let it retry in the next reconciles.

**Comment by robbie-demuth** [comment] 2023-02-24 14:06
> We can't assume that the resourceVersion always be a string of increasing integer and use it to compare which one is newer

This is true, but we can use `generation` to some extent (it looks like it's not incremented for metadata-only updates)

Even if we take a naive approach and prioritize cache updates from the informer, the cache will be up-to-date for a period of time before becoming outdated again in the scenario you described.

> To solve your problem, you could use retry.RetryOnConflict to do a quick retry. And if it still fails, which may be caused by slow network transmission or apiserver suffering pressure, you have to return an error in reconcile and let it retry in the next reconciles

This is an interesting idea that our team hadn't considered. We'll take a look, thanks!

**Comment by alvaroaleman** [comment] 2023-02-25 19:12
> This is true, but we might be able to use generation to some extent 

No, generation is only implemented by a subset of all resources.

We don't have a way to know if the version we get from the infomer is newer/older than what we got from the write, hence this is not possible.

**Closed** 2024-01-19 02:59 UTC
Labels: lifecycle/rotten

**Comment by robbie-demuth** [comment] 2026-04-22 22:22
I think this KEP that graduated to beta in 1.36 addresses this issue: 

https://github.com/kubernetes/enhancements/issues/5647

**Comment by alvaroaleman** [comment] 2026-04-22 22:35
Yes, we are aware, https://github.com/kubernetes-sigs/controller-runtime/issues/3320 is the current issue for the topic
