### ISSUE TITLE
source.Channel gets a nil value for stop channel

### ISSUE THREAD

**Issue by mhrivnak** [kubernetes-sigs/controller-runtime#149] opened 2018-09-18 21:35 UTC
## Problem

When adding a [Channel](https://github.com/kubernetes-sigs/controller-runtime/blob/bb5ef08d8d98e5d40654e0cecc9cc336de642ae4/pkg/source/source.go#L102-L124) to a controller by calling `Watch()`, [InjectStopChannel](https://github.com/kubernetes-sigs/controller-runtime/blob/bb5ef08d8d98e5d40654e0cecc9cc336de642ae4/pkg/source/source.go#L128-L136) gets called with a value of `nil` instead of a real channel.

This appears to be because nothing sets the value of [`stop`](https://github.com/kubernetes-sigs/controller-runtime/blob/01696e9d61766e4821aab89efe5f06c2c6153e5c/pkg/manager/internal.go#L76) before `Watch()` gets called. The value of `stop` only gets set once the manager's `Start()` method is called.

Here's the order of operations:

1. Manager gets created
2. Controller gets created and added to the manager
3. Controller's `Watch()` method gets called with the new `Channel` as an argument
4. Manager's `Start()` method gets called, with a stop channel being passed in. This is the opportunity for a stop channel to be provided by a controller author.
5. The manager's `Start()` method calls each controller's `Start()` method, also passing through the stop channel.

At step 3, the manager's stop channel gets injected into the Channel. But the manager's stop channel doesn't get set until step 4, so at step 3 it has a `nil` value. 

## Workaround

The controller author can call `InjectStopChannel` directly and pass it the same channel they'll later pass to the manager's `Start()` method. But the `InjectStopChannel` method is clearly documented as not being intended for this purpose, nor is this approach helpful to the controller author.

**Comment by DirectXMan12** [comment] 2018-09-19 08:08
duplicate of https://github.com/kubernetes-sigs/controller-runtime/issues/103

**Closed** 2018-11-28 19:18 UTC
