### ISSUE TITLE
Ability to create watches for different namespaces

### ISSUE THREAD

**Issue by lulf** [kubernetes-sigs/controller-runtime#687] opened 2019-11-20 21:10 UTC
We have a use case where we have 2 namespaced resources, and a controller watching resources of type A in all namespace, but it would also like to watch resources of type B for a single specific namespace (for instance based on which namespace an instance of 'A' exists). At present, this is not possible to watch instances of B in a specific namespace. The alternative of watching resource B in all namespaces is not desired (lets say B is the Secret type, and we would like to avoid overly wide privileges for the operator).

Right now namespace is configured at the manager level, but ideally for our use case, we should be able to specify a namespace when watching resources, similar to what was discussed here: https://github.com/kubernetes-sigs/controller-runtime/issues/124#issuecomment-417438810

What would be required to allow the above, and is a contribution of that something that would get accepted?

**Comment by alvaroaleman** [comment] 2019-11-22 18:32
IMHO this is a duplicate of #244 . Feel free to re-open if you disagree.
/close

**Closed by alvaroaleman** 2019-11-22 18:32 UTC

**Comment by lulf** [comment] 2019-11-22 19:03
@alvaroaleman Reading that issue, I agree its similar, but my main requirement is to avoid the need to grant more permissions to the controller than what is needed. I.e. filtering by namespace client-side would not be sufficient. If you want to keep this closed, I can perhaps add a comment to that issue instead.
