### ISSUE TITLE
Sets a custom filter on watch or list resource from apiserver

### ISSUE THREAD

**Issue by liuxin95** [kubernetes-sigs/controller-runtime#1227] opened 2020-10-23 17:08 UTC
**Hi All:**
I have a requirement: to reconcile changes in the ConfigMap resource named app-config
In client-go i can use the informers.WithTweakListOptions function to solve this problem
For example:
```
cmInformer := v13.NewFilteredConfigMapInformer(clientset, namespace, resyncPeriod,
		cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, func(options *v1.ListOptions) {
			options.FieldSelector = fields.OneTermEqualSelector("metadata.name", "app-config").String()
		})

cmInformer.AddEventHandler(xxxx)
```

but if i use kubernetes-sigs/controller-runtime, I noticed that kubernetes-sigs/controller-runtime does not provide any method to filter when the watch apiserver resource changes 
How can i do it ？

thank you for you reply

**Comment by alvaroaleman** [comment] 2020-10-25 20:49
Closing as duplicate of https://github.com/kubernetes-sigs/controller-runtime/issues/244
/close

**Closed** 2020-10-25 20:49 UTC
