### ISSUE TITLE
Panic creating kubebuilder-envtest cache directory

### ISSUE THREAD

**Issue by hanlins** [kubernetes-sigs/controller-runtime#1845] opened 2022-03-24 18:34 UTC
Encountered following error:
```
$ kubectl -n infra logs -f eks-provider-db6d54fd5-gzx7t
panic: mkdir /.cache: permission denied

goroutine 1 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/testing/addr.init.0()
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/addr/manager.go:51 +0xda
```
controller-runtime version: `v0.9.6`
golang version: `go1.17.7`

The issue is related to the `init` function that sets up `kubebuilder-envtest` caching directory, see [code](https://github.com/kubernetes-sigs/controller-runtime/blob/v0.9.6/pkg/internal/testing/addr/manager.go#L44-L53).

The [`UserCacheDir`](https://github.com/golang/go/blob/go1.17.7/src/os/file.go#L393-L442) is supposed to return the cache directory location. In the pod setup, `HOME` is set to `/` and `XDG_CACHE_HOME` is not set so `UserCacheDir` ends up returning `//.cache` without emitting error. However, the process doesn't have permission to create directory under that location and thus it paniced.

One walkaround is to manually set `XDG_CACHE_HOME` to `/tmp` in deployment spec. It would be great if we have logic that fall back to using `/tmp` on permission issues.

**Comment by skitt** [comment] 2022-04-05 07:31
This is a duplicate of #1799.

**Closed** 2022-04-23 22:51 UTC

**Comment by georgettica** [comment] 2022-05-16 07:31
I had this issue and was thinking it was something else. thank you for creating the duplicate! I didn't find it with my google-foo skills.

I will mention on the duplicate issue that note
